#Vaadin Copilot Integration Runtime Properties
#Thu Apr 02 20:15:04 IST 2026
endpoint=http\://127.0.0.1\:62156/vaadin/copilot-8efa3e53-2b19-4e21-93e9-dba0ed43166a
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
